{{- if .Values.snowflake.private_key_password_secret.name }}

apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.snowflake.private_key_password_secret.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{ include "snowalert.labels" . | nindent 4 }}
    "app.kubernetes.io/name": '{{ template "snowalert.name" }}'
    "app.kubernetes.io/managed-by": "{{ .Release.Service }}"
    "app.kubernetes.io/instance": "{{ .Release.Name }}"
type: Opaque
data:
  {{ if .Values.snowflake.secret.private_key_password }}
  private_key_password: {{ .Values.snowflake.secret.private_key_password | b64enc | quote }}
  {{ end }}
  {{ if .Values.snowflake.secret.private_key }}
  private_key: {{ .Values.snowflake.secret.private_key | b64enc | b64enc | quote }}
  {{ end }}
{{- end }}
