{{- if and .Values.snowflake.secret.private_key_password .Values.snowflake.secret.private_key }}

apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.snowflake.private_key_password_secret.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    "app.kubernetes.io/name": "{{ template "snowalert.name" . }}"
    "app.kubernetes.io/managed-by": "{{ .Release.Service }}"
    "app.kubernetes.io/instance": "{{ .Release.Name }}"
type: Opaque
data:
  private_key_password: {{ .Values.snowflake.secret.private_key_password | b64enc | quote }}
  private_key: {{ .Values.snowflake.secret.private_key | b64enc | b64enc | quote }}

{{- end }}
